FROM nvidia/cuda:12.4.1-devel-ubuntu22.04

# Installa dipendenze di sistema
RUN apt-get update && apt-get install -y curl wget git build-essential ca-certificates && rm -rf /var/lib/apt/lists/*

# Installa Rust 1.87.0
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y --default-toolchain 1.87.0
ENV PATH="/root/.cargo/bin:$PATH"

# Installa Miniconda (qui scegli la versione per python3.8, ma anche la latest va bene)
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py310_4.12.0-Linux-x86_64.sh -O /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -b -p /opt/conda && \
    rm /tmp/miniconda.sh && \
    /opt/conda/bin/conda install -n base conda=25.3.1 -y

ENV PATH=/opt/conda/bin:$PATH

# Copia il file environment.yml dentro il container
COPY environment.yml /tmp/environment.yml

# Crea ambiente conda con python 3.8
RUN conda env create -f /tmp/environment.yml




# Imposta l'ambiente di default
SHELL ["conda", "run", "-n", "dnabert", "/bin/bash", "-c"]

# (opzionale) attiva l’ambiente automaticamente (per esempio quando fai ENTRYPOINT o CMD)
ENV PATH=/opt/conda/envs/dnabert/bin:$PATH

# Imposta la working directory
WORKDIR /workspace

CMD ["python", "--version"]
